TWITTER_API_KEY = "XbVphKtDlXBPB9Pa8NHvLH7fj"
TWITTER_API_SECRET = "IugbVe8sk5gmx4oQAYBWoAR6YncNy4rzBDRZw9YYRHVYrDP2ZZ"
TWITTER_BEARER = "AAAAAAAAAAAAAAAAAAAAAFC55QEAAAAAchbWA0V%2B8N1I%2FQe5nC%2BVp1JEvCo%3D625lhH2dZKzcYHFjHIOmeDCmeXasyezAA0SAPz9vQxvK7jlyeK"

REDDIT_CLIENT_ID = "client_id"
REDDIT_SECRET = "client_secret"
REDDIT_AGENT = "scraper_bot"
